name: Bug Report
description: Report bugs about Pyasys. Please add information to the form fields below. After submitting, you will be in touch with our devs and community experts shortly.
labels: [ "status: bug", "type: bug" ]
body:
  - type: textarea
    attributes:
      label: Behavior
      description: What the error does. Explain this clearly to ensure a solution can be given to you.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: How To Reproduce
      description: Explain how to create the issue. For example, provide information about when the bug occurs.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected Solution that Does Not Work
      description: Did you try a solution that you expected to work, but it did not? Share it here. If you do not have this info, this field is not required.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: Would you like to send us additional information? You can do so here.
    validations:
      required: false
