name: Behavior Bug or Plugin Incompatibility
description: Report issues with plugin incompatbility or other behavior related issues.
labels: [ "status: bug", "type: bug" ]
body:
  - type: textarea
    attributes:
      label: Behavior
      description: What the error does. Explain this clearly to ensure a solution can be given to you.
    validations:
      required: true
